[CmdletBinding()]
param(
    [string]$ApplicationPath = "/var/www/transcribed-subtitle-extension/app/backend/current",
    [string]$PhpPath = "php",
    [string]$WorkerUser = "forge",
    [int]$WorkerTimeoutSeconds = 1200,
    [int]$StopWaitSeconds = 1260,
    [int]$SleepSeconds = 0,
    [int]$Tries = 0,
    [int]$MemoryMb = 256,
    [int]$MaxTimeSeconds = 3600,
    [string]$LogDirectory = "/var/log/transcribed-subtitle-extension",
    [string]$OutputPath
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$Artisan = Join-Path $ScriptDir "..\runtime\artisan.ps1"

$runtimeOutput = & $Artisan "subtitles:runtime-check" "--json" "--no-ansi"

if ($LASTEXITCODE -ne 0) {
    throw "Could not read subtitle runtime configuration."
}

$runtime = ($runtimeOutput -join "`n") | ConvertFrom-Json
$groups = $runtime.summary.subtitleWorkerGroups
$lines = New-Object System.Collections.Generic.List[string]

$lines.Add("; Generated by scripts/ops/render-supervisor-config.ps1")
$lines.Add("; Copy to /etc/supervisor/conf.d/transcribed-subtitle-extension-workers.conf, then run:")
$lines.Add("; sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl restart tse-*:*")
$lines.Add("")

foreach ($group in $groups) {
    $program = "tse-$($group.name)"
    $queues = ($group.queues -join ",")
    # Each group stays below its own connection's retry_after; older runtime output has no timeout.
    $timeout = if ($group.timeout_seconds) { [int]$group.timeout_seconds } else { $WorkerTimeoutSeconds }

    $lines.Add("[program:$program]")
    $lines.Add("process_name=%(program_name)s_%(process_num)02d")
    $lines.Add("directory=$ApplicationPath")
    $lines.Add("command=$PhpPath artisan queue:work $($group.connection) --queue=$queues --sleep=$SleepSeconds --tries=$Tries --timeout=$timeout --memory=$MemoryMb --max-time=$MaxTimeSeconds")
    $lines.Add("autostart=true")
    $lines.Add("autorestart=true")
    $lines.Add("stopasgroup=true")
    $lines.Add("killasgroup=true")
    $lines.Add("user=$WorkerUser")
    $lines.Add("numprocs=$($group.worker_count)")
    $lines.Add("redirect_stderr=true")
    $lines.Add("stdout_logfile=$LogDirectory/$program.log")
    $lines.Add("stopwaitsecs=$StopWaitSeconds")
    $lines.Add("")
}

$content = $lines -join [Environment]::NewLine

if ($OutputPath) {
    $directory = Split-Path -Parent $OutputPath

    if ($directory) {
        New-Item -ItemType Directory -Force -Path $directory | Out-Null
    }

    Set-Content -LiteralPath $OutputPath -Value $content
    Write-Host "Supervisor config written to $OutputPath"
} else {
    $content
}
